spring:
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
  flyway:
    clean-disabled: true
app:
  collaboration:
    redis-enabled: false
logging:
  level:
    org.testcontainers: info
