spring:
  mail:
    host: ${SES_SMTP_HOST}
    port: ${SES_SMTP_PORT:587}
    username: ${SES_SMTP_USERNAME}
    password: ${SES_SMTP_PASSWORD}
    properties.mail.smtp:
      auth: true
      starttls.enable: true
server:
  servlet:
    session:
      cookie:
        secure: true
app:
  collaboration:
    allowed-origins: ${WEBSOCKET_ALLOWED_ORIGINS}
